In [2]:
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras import models

In [3]:
model = models.load_model("model from kaggle.h5")

In [25]:
def image_predict(path):
    #loading image from given path and changing it in array
    test_image = image.load_img(path,target_size=(224,224,3))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image,axis=0)
    print(test_image)
    #making prediction
    result = model.predict(test_image)
    print(result)
    #now checking result
    result = np.argmax(result)
    print(result)
    if result == 0:
        prediction = 'Bacterial leaf blight'
    elif result == 1:
        prediction = 'Brown spot'
    else:
        prediction = 'Leaf smut'
    return prediction

In [26]:
print("Correct Bacterial-leaf-blight And Predict :",image_predict("datasets/rice_Bacterial-leaf-blight.jpg"))
print("Correct Leaf_smut And Predict :",image_predict("datasets/rice_Leaf_smut.jpg"))
print("Correct Leaf_smut And Predict :",image_predict("datasets/rice_leaf_smut1.jpg"))
print("Correct brown_spot And Predict :",image_predict("datasets/rice_brown_leaf.jpg"))

[[[[147. 158.  90.]
   [145. 158.  88.]
   [144. 154.  85.]
   ...
   [ 98.  45.  29.]
   [102.  49.  33.]
   [ 98.  46.  33.]]

  [[153. 162.  97.]
   [155. 164.  99.]
   [145. 155.  86.]
   ...
   [ 97.  48.  33.]
   [102.  49.  41.]
   [ 98.  46.  35.]]

  [[164. 171. 103.]
   [155. 165.  96.]
   [150. 158.  98.]
   ...
   [ 99.  50.  35.]
   [ 97.  47.  38.]
   [ 96.  43.  37.]]

  ...

  [[154. 143.  98.]
   [146. 133.  89.]
   [148. 133.  90.]
   ...
   [250. 251. 253.]
   [249. 250. 255.]
   [243. 247. 255.]]

  [[163. 150. 106.]
   [150. 137.  93.]
   [146. 131.  92.]
   ...
   [250. 251. 253.]
   [247. 248. 252.]
   [243. 248. 252.]]

  [[161. 150. 105.]
   [151. 138.  96.]
   [145. 132.  90.]
   ...
   [251. 251. 251.]
   [250. 251. 253.]
   [247. 248. 253.]]]]
[[9.9992061e-01 5.0491257e-05 2.8847076e-05]]
0
Correct Bacterial-leaf-blight And Predict : Bacterial leaf blight
[[[[116.  76.  24.]
   [131.  61.   9.]
   [220. 196. 134.]
   ...
   [ 41.  77.  16.]
   [ 38.  77.  14